// <auto-generated />
using System;
using System.Collections.Generic;
using IonioPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IonioPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IonioPortal.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MajorPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("RankingOptions")
                        .HasColumnType("integer[]");

                    b.Property<int?>("SliderMax")
                        .HasColumnType("integer");

                    b.Property<int?>("SliderMin")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolboxPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4,\"\\u039A\\u0394\\u0395\":1}",
                            QuestionId = 1,
                            Text = "Training an AI on some weird dataset to see what happens",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":1,\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 1,
                            Text = "Building that app idea that's been living rent-free in your head",
                            ToolboxPoints = "{\"TB4\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 3,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 1,
                            Text = "Setting up a home security lab or trying to crack your own system",
                            ToolboxPoints = "{\"TB5\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 4,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":2,\"\\u03A8\\u039C\\u0391\\u0394\":3}",
                            QuestionId = 1,
                            Text = "Making something visual/interactive that makes people go \"wait, how'd you do that?\"",
                            ToolboxPoints = "{\"TB2\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 5,
                            MajorPoints = "{}",
                            QuestionId = 2,
                            SliderMax = 10,
                            SliderMin = 1,
                            Text = " When coding, I'm more 1=Theory/Elegant, 10=Practical/Ships",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 7,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":3}",
                            QuestionId = 3,
                            Text = "🤖 \"AI just discovered something doctors missed for 50 years\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 8,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3}",
                            QuestionId = 3,
                            Text = "💰 \"College dropout's app just hit $10M revenue\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 9,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":3}",
                            QuestionId = 3,
                            Text = "🔓 \"How hackers stole $600M in cryptocurrency\"",
                            ToolboxPoints = "{\"TB5\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 10,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":2,\"\\u03A8\\u039C\\u0391\\u0394\":1}",
                            QuestionId = 3,
                            Text = "🎨 \"The insane tech behind that movie scene\"",
                            ToolboxPoints = "{\"TB2\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 11,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":3,\"\\u039A\\u0394\\u0395\":1}",
                            QuestionId = 3,
                            Text = "🧮 \"The beautiful math that makes the internet work\"",
                            ToolboxPoints = "{\"TB1\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 12,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":2}",
                            QuestionId = 3,
                            Text = "📚 \"Why students can't learn [subject] and how to fix it\"",
                            ToolboxPoints = "{\"TB3\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 13,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 4,
                            Text = "\"I wonder if I could predict/model/analyze this...\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 14,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 4,
                            Text = "\"I could build something that solves this problem\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 15,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 4,
                            Text = "\"That's definitely a security risk waiting to happen\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 16,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 4,
                            Text = "\"Why is this so hard to use? I could make this better\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 17,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 5,
                            Text = "🔬 Jupyter Notebook + unlimited datasets",
                            ToolboxPoints = "{\"TB1\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 18,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 5,
                            Text = "☁️ Full cloud deployment setup + API access",
                            ToolboxPoints = "{\"TB4\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 19,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 5,
                            Text = "🛡️ Kali Linux + all the hacking tools (ethical, obviously)",
                            ToolboxPoints = "{\"TB5\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 20,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 5,
                            Text = "🎮 Unity/Unreal Engine OR your favorite creative suite",
                            ToolboxPoints = "{\"TB2\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 21,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":3}",
                            QuestionId = 6,
                            Text = "The 'make it look pretty' person",
                            ToolboxPoints = "{\"TB2\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 22,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3}",
                            QuestionId = 6,
                            Text = "The pure researcher",
                            ToolboxPoints = "{\"TB1\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 23,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":3}",
                            QuestionId = 6,
                            Text = "The 'move fast break things' person",
                            ToolboxPoints = "{\"TB5\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 24,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":2,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 6,
                            Text = "The backend-only person",
                            ToolboxPoints = "{\"TB4\":1}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 25,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 7,
                            Text = "🧬 Researcher's Algorithm Breakthrough Advances Medicine",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 26,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 7,
                            Text = "📈 Startup's Platform Now Serves 10M Users Daily",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 27,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 7,
                            Text = "🛡️ Security Expert Prevents Billion-Dollar Data Breach",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 28,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 7,
                            Text = "🌟 Creator's Work Changes How 100k People Learn/Play",
                            ToolboxPoints = "{\"TB2\":2}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 29,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 8,
                            Text = "🧠 How to make AI actually intelligent",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 30,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3}",
                            QuestionId = 8,
                            Text = "🚀 How to build systems that don't crash",
                            ToolboxPoints = "{\"TB4\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 31,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 8,
                            Text = "🔐 How hackers think and how to stop them",
                            ToolboxPoints = "{\"TB5\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 32,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 8,
                            Text = "🎨 How to make interfaces that feel magical",
                            ToolboxPoints = "{\"TB2\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 33,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 8,
                            Text = "🧮 The deep theory that makes everything else possible",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 34,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":2}",
                            QuestionId = 8,
                            Text = "👨‍🏫 How to explain complex stuff so anyone can get it",
                            ToolboxPoints = "{\"TB3\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 35,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 9,
                            Text = "Launches into the technical details of the algorithm/problem",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 36,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 9,
                            Text = "\"Something that could actually be useful for [specific people]\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 37,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 9,
                            Text = "\"Trying to break/secure this system\" shows security logs",
                            ToolboxPoints = "{\"TB5\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 38,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 9,
                            Text = "Just shows them the demo/interface \"Check this out!\"",
                            ToolboxPoints = "{\"TB2\":4}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 39,
                            MajorPoints = "{\"\\u0392\\u03A5\\u039D\":4}",
                            QuestionId = 10,
                            Text = "\"Wait... why is it doing THAT? This is actually interesting\"",
                            ToolboxPoints = "{}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 40,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":4}",
                            QuestionId = 10,
                            Text = "\"Ugh, this delays the launch timeline\"",
                            ToolboxPoints = "{\"TB4\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 41,
                            MajorPoints = "{\"\\u039A\\u0394\\u0395\":4}",
                            QuestionId = 10,
                            Text = "\"Could someone exploit this? Let me check...\"",
                            ToolboxPoints = "{\"TB5\":3}",
                            Weight = 1
                        },
                        new
                        {
                            Id = 42,
                            MajorPoints = "{\"\\u03A8\\u039C\\u0391\\u0394\":3,\"\\u0392\\u03A5\\u039D\":1}",
                            QuestionId = 10,
                            Text = "\"How do I explain this to users without causing panic?\"",
                            ToolboxPoints = "{\"TB2\":4}",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("IonioPortal.Models.AnswerQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("AnswersQuestion");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            AnswerId = 1
                        },
                        new
                        {
                            QuestionId = 1,
                            AnswerId = 2
                        },
                        new
                        {
                            QuestionId = 1,
                            AnswerId = 3
                        },
                        new
                        {
                            QuestionId = 1,
                            AnswerId = 4
                        },
                        new
                        {
                            QuestionId = 2,
                            AnswerId = 5
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 7
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 8
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 9
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 10
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 11
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerId = 12
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerId = 13
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerId = 14
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerId = 15
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerId = 16
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerId = 17
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerId = 18
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerId = 19
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerId = 20
                        },
                        new
                        {
                            QuestionId = 6,
                            AnswerId = 21
                        },
                        new
                        {
                            QuestionId = 6,
                            AnswerId = 22
                        },
                        new
                        {
                            QuestionId = 6,
                            AnswerId = 23
                        },
                        new
                        {
                            QuestionId = 6,
                            AnswerId = 24
                        },
                        new
                        {
                            QuestionId = 7,
                            AnswerId = 25
                        },
                        new
                        {
                            QuestionId = 7,
                            AnswerId = 26
                        },
                        new
                        {
                            QuestionId = 7,
                            AnswerId = 27
                        },
                        new
                        {
                            QuestionId = 7,
                            AnswerId = 28
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 29
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 30
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 31
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 32
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 33
                        },
                        new
                        {
                            QuestionId = 8,
                            AnswerId = 34
                        },
                        new
                        {
                            QuestionId = 9,
                            AnswerId = 35
                        },
                        new
                        {
                            QuestionId = 9,
                            AnswerId = 36
                        },
                        new
                        {
                            QuestionId = 9,
                            AnswerId = 37
                        },
                        new
                        {
                            QuestionId = 9,
                            AnswerId = 38
                        },
                        new
                        {
                            QuestionId = 10,
                            AnswerId = 39
                        },
                        new
                        {
                            QuestionId = 10,
                            AnswerId = 40
                        },
                        new
                        {
                            QuestionId = 10,
                            AnswerId = 41
                        },
                        new
                        {
                            QuestionId = 10,
                            AnswerId = 42
                        });
                });

            modelBuilder.Entity("IonioPortal.Models.ExaminationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Exams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("exams")
                        .HasAnnotation("Relational:JsonPropertyName", "exams");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.HasKey("Id");

                    b.ToTable("exam_schedules", (string)null);
                });

            modelBuilder.Entity("IonioPortal.Models.Majors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mweight")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bioinformatics and Computational Intelligence",
                            Mweight = 48,
                            Name = "ΒΥΝ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cyber-security and Communication Networks",
                            Mweight = 35,
                            Name = "ΚΔΕ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Digital Transformation and Data Analytics",
                            Mweight = 66,
                            Name = "ΨΜΑΔ"
                        });
                });

            modelBuilder.Entity("IonioPortal.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("MajorPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("RankingOptions")
                        .HasColumnType("integer[]");

                    b.Property<int?>("SliderMax")
                        .HasColumnType("integer");

                    b.Property<int?>("SliderMin")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolboxPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Index = 1,
                            MajorPoints = "{}",
                            Text = "🎮 Saturday night, laptop open. What are you actually doing?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            Index = 2,
                            MajorPoints = "{}",
                            Text = "📊 When coding, I'm more 1=Theory/Elegant, 10=Practical",
                            ToolboxPoints = "{}",
                            Type = "slider",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Index = 3,
                            MajorPoints = "{}",
                            Text = "🔥 You're doom-scrolling at 2am. What makes you stop and actually click?",
                            ToolboxPoints = "{}",
                            Type = "multiple",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            Index = 4,
                            MajorPoints = "{}",
                            Text = "💭 Real talk - which thought do you have most often?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            Index = 5,
                            MajorPoints = "{}",
                            Text = "🎯 Your laptop can only run ONE thing for a month. Choose wisely:",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            Index = 6,
                            MajorPoints = "{}",
                            Text = "🎪 Group project time. Which role do you secretly hope to avoid?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            Index = 7,
                            MajorPoints = "{}",
                            Text = "🎬 Five years from now, which headline makes you feel something?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 8,
                            Index = 8,
                            MajorPoints = "{}",
                            Text = "🔮 You get a magic 4-hour block where you're guaranteed to learn anything. What do you pick?",
                            ToolboxPoints = "{}",
                            Type = "rank",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            Index = 9,
                            MajorPoints = "{}",
                            Text = "💬 Your friend asks \"what are you working on?\" - what's your honest answer?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            Index = 10,
                            MajorPoints = "{}",
                            Text = "🎯 Real scenario: You just discovered a bug. What's your first actual thought?",
                            ToolboxPoints = "{}",
                            Type = "single",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("IonioPortal.Models.QuestionForMajor", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("QuestionId", "MajorId");

                    b.HasIndex("MajorId");

                    b.ToTable("QuestionForMajor");
                });

            modelBuilder.Entity("IonioPortal.Models.QuestionForToolbox", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolboxId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("QuestionId", "ToolboxId");

                    b.HasIndex("ToolboxId");

                    b.ToTable("QuestionForToolbox");
                });

            modelBuilder.Entity("IonioPortal.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IonioPortal.Models.Schedules", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("academic_year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_year");

                    b.Property<string>("courses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("courses");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.HasKey("id");

                    b.ToTable("class_schedules", (string)null);
                });

            modelBuilder.Entity("IonioPortal.Models.ScoringRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScoringRules");
                });

            modelBuilder.Entity("IonioPortal.Models.Toolboxes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TWeight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Toolboxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Theoretical Computer Science",
                            Name = "TB1",
                            TWeight = 7
                        },
                        new
                        {
                            Id = 2,
                            Description = "Interaction",
                            Name = "TB2",
                            TWeight = 23
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pedagogy",
                            Name = "TB3",
                            TWeight = 7
                        },
                        new
                        {
                            Id = 4,
                            Description = "Software",
                            Name = "TB4",
                            TWeight = 14
                        },
                        new
                        {
                            Id = 5,
                            Description = "Humanistic Dimensions of Computer Science",
                            Name = "TB5",
                            TWeight = 24
                        });
                });

            modelBuilder.Entity("IonioPortal.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EnrolledCourses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasCompletedTest")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<string>("Minor")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IonioPortal.Models.UserRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrimaryMajor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryToolbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasoningJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryMajor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryToolbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRecommendation");
                });

            modelBuilder.Entity("IonioPortal.Models.weekly_menus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("days")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("week_end")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("week_start")
                        .HasColumnType("timestamptz");

                    b.HasKey("id");

                    b.ToTable("weekly_menus");
                });

            modelBuilder.Entity("UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRecommendationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserRecommendationId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("IonioPortal.Models.Answer", b =>
                {
                    b.HasOne("IonioPortal.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IonioPortal.Models.AnswerQuestion", b =>
                {
                    b.HasOne("IonioPortal.Models.Answer", "Answer")
                        .WithMany("AnswerQuestions")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IonioPortal.Models.Question", "Question")
                        .WithMany("AnswerQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IonioPortal.Models.QuestionForMajor", b =>
                {
                    b.HasOne("IonioPortal.Models.Majors", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IonioPortal.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IonioPortal.Models.QuestionForToolbox", b =>
                {
                    b.HasOne("IonioPortal.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IonioPortal.Models.Toolboxes", "Toolbox")
                        .WithMany()
                        .HasForeignKey("ToolboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Toolbox");
                });

            modelBuilder.Entity("IonioPortal.Models.RefreshToken", b =>
                {
                    b.HasOne("IonioPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IonioPortal.Models.UserRecommendation", b =>
                {
                    b.HasOne("IonioPortal.Models.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAnswer", b =>
                {
                    b.HasOne("IonioPortal.Models.UserRecommendation", "UserRecommendation")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRecommendation");
                });

            modelBuilder.Entity("IonioPortal.Models.Answer", b =>
                {
                    b.Navigation("AnswerQuestions");
                });

            modelBuilder.Entity("IonioPortal.Models.Question", b =>
                {
                    b.Navigation("AnswerQuestions");

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("IonioPortal.Models.User", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("IonioPortal.Models.UserRecommendation", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
